### ISSUE TITLE
垂直居中效果不一致

### ISSUE THREAD

**Issue by linjiaqin12138** [Sweet-KK/css-layout#4]
第二章“垂直居中”的第四个小节“单个块级元素”的第三点“使用flex实现”中
```css
#parent{
    display: flex;
    align-items: center;
}

//或

#parent{display: flex;}
.son{align-self: center;}
```
效果如下
![image](https://user-images.githubusercontent.com/38090888/138551757-37b57d58-c076-42b4-8324-e7ee75b26af4.png)
```css
#parent{
    display: flex;
    flex-direction: column;
    justify-content: center;
}
```
效果如下
![image](https://user-images.githubusercontent.com/38090888/138551877-05159dd2-44da-4764-84f1-0a2309edff7a.png)
效果不一致，后者才是正确的
